### ISSUE TITLE
Firefox on infinite loop Uncaught (in promise) TypeError: registration.active is null

### ISSUE THREAD

**Issue by erikpeik** [AxaFrance/react-oidc#946]
### Issue and Steps to Reproduce

**Uncaught (in promise) TypeError: registration.active is null**

For some reason on Firefox, there will be an infinite loop on Loading. On Chrome everything works mostly alright. I'm using Okta as an identity provider, but the same problems seem to appear when using IdentityServer Demo. 

### Versions
react-oidc [v6.13.4](https://github.com/AxaGuilDEv/react-oidc/releases/tag/v6.13.4) & [v6.14.0](https://github.com/AxaGuilDEv/react-oidc/releases/tag/v6.14.0) tested
Firefox 109.0 (64-bit)

### Screenshots
![registration.active is null](https://user-images.githubusercontent.com/52178013/216364473-fcaf0924-2a1a-402f-83b3-8e935dc63497.png)
![image](https://user-images.githubusercontent.com/52178013/216369986-5339c0d6-fc99-492b-8dc2-8b6b96579bcd.png)

#### Expected

To work the same way as it works on Chrome as it should be. 

### Additional Details

- Installed packages:
```json
  "dependencies": {
    "@axa-fr/react-oidc": "^6.14.0",
    "@emotion/react": "^11.10.5",
    "@emotion/styled": "^11.10.5",
    "@mui/icons-material": "^5.11.0",
    "@mui/material": "^5.11.7",
    "@reduxjs/toolkit": "^1.9.2",
    "@types/jest": "^29.4.0",
    "@types/react": "^18.0.27",
    "@types/react-dom": "^18.0.10",
    "@types/react-helmet": "^6.1.6",
    "axios": "^1.3.1",
    "bootstrap": "^5.2.3",
    "dayjs": "^1.11.7",
    "fhirpath": "^3.3.1",
    "http-proxy-middleware": "^2.0.6",
    "jquery": "^3.6.3",
    "markdown-to-jsx": "^7.1.9",
    "merge": "^2.1.1",
    "oidc-client": "^1.11.5",
    "oidc-client-ts": "^2.2.1",
    "onchange": "^7.1.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-helmet": "^6.1.0",
    "react-redux": "^8.0.5",
    "react-router-bootstrap": "^0.26.2",
    "react-scripts": "^5.0.1",
    "reactstrap": "^9.1.5",
    "redux": "^4.2.1",
    "rimraf": "^4.1.2",
    "web-vitals": "^3.1.1",
    "workbox-background-sync": "^6.5.4",
    "workbox-broadcast-update": "^6.5.4",
    "workbox-cacheable-response": "^6.5.4",
    "workbox-core": "^6.5.4",
    "workbox-expiration": "^6.5.4",
    "workbox-google-analytics": "^6.5.4",
    "workbox-navigation-preload": "^6.5.4",
    "workbox-precaching": "^6.5.4",
    "workbox-range-requests": "^6.5.4",
    "workbox-routing": "^6.5.4",
    "workbox-strategies": "^6.5.4",
    "workbox-streams": "^6.5.4"
  },
```
- App.tsx with oidcConfiguration
```javascript
import { Routes, Route, BrowserRouter as Router } from "react-router-dom";
import AppRoutes from "./AppRoutes";
import Layout from "./components/Layout";
import { OidcProvider } from "@axa-fr/react-oidc";

const oidcConfig = {
  client_id: process.env.REACT_APP_CLIENT_ID!,
  redirect_uri: window.location.origin + "/authentication/callback",
  silent_redirect_uri:
    window.location.origin + "/authentication/silent-callback",
  scope: "openid profile email roles",
  authority: `https://dev-XXXXXXX.okta.com/oauth2/default`,
  service_worker_relative_url: "/OidcServiceWorker.js",
  service_worker_only: false,
};

const baseUrl = document.getElementsByTagName("base")[0].getAttribute("href")!;

const App = () => {

  return (
    <OidcProvider configuration={oidcConfig} onEvent={onEvent}>
      <Router basename={baseUrl}>
        <Layout>
          <Routes>
            {AppRoutes.map((route, index) => {
              const { element, ...rest } = route;
              return <Route key={index} {...rest} element={element} />;
            })}
          </Routes>
        </Layout>
      </Router>
    </OidcProvider>
  );
};

export default App;
```

**Comment by erikpeik** [comment]
Same problem appears on Safari. Only Chrome seems to work.

**Comment by guillaume-chervet** [comment]
hi @erikpeik , thank you very much for your issue.

That's very strange. I use firefox 109.0.1 (64 bits) and online demo work.

Do you encounter this behavior in local ?

Does the demo works for you with firefox ?
https://black-rock-0dc6b0d03.1.azurestaticapps.net/

It looks like to have one a ServiceWorker Update on your debug screen.

![image](https://user-images.githubusercontent.com/52236059/216698095-bb5f40f5-d5a1-4511-b765-c12f4a870fcd.png)

**Comment by guillaume-chervet** [comment]
hi @erikpeik,

what does look like you baseUrl in <Router basename={baseUrl}>?

**Comment by erikpeik** [comment]
Hey,

With the demo, I have no problems. Tried with that link and also cloned the repo and launched that demo locally and everything seems to work.

Also changed the oidcProvieders configuration to match my provider and still no errors. 
![Animation](https://user-images.githubusercontent.com/52178013/216912126-12b710b6-5152-419a-a38d-bc93b301780a.gif)

**Comment by erikpeik** [comment]
However, the video that was uploaded in the last post still shows a bit more of the behaviour on firefox with my project. The project is also deployed to Azure App Service, but I cannot unfortunately share that. Everything works greatly on Chrome login, logout etc. but on firefox and other browsers cannot even get to the page.

I didn't totally get what you meant by baseUrl in. Where I can find it? @guillaume-chervet

**Comment by guillaume-chervet** [comment]
Hi @erikpeik , do you have serviceWorker files well copied in your public directory ?

**Comment by erikpeik** [comment]
Both OidcServiceWorker.js & OidcTrustedDomains.js are well copied in the public/ folder.

**Comment by guillaume-chervet** [comment]
hi @erikpeik ,

I published 6.14.2-alpha0 for you to test. I think that it may happen during a ServiceWorker update.

**Comment by erikpeik** [comment]
Hey @guillaume-chervet ,

Thanks for your time and effort! Unfortunately, it didn't fully fix my problems. 

I don't anymore get that `Uncaught (in promise) TypeError: registration.active is null` but still it will infinite loop on every page.

The only thing that will come to the console is `oidc:default:tryKeepExistingSessionAsync_begin 
Object {  }` but it just keeps navigating to the same URL.

**Comment by guillaume-chervet** [comment]
Thank you @erikpeik  for the feedback. It is strange. It is like if your service worker does not want to update.
What happen if you clear it manually from debug panel?

**Comment by erikpeik** [comment]
I didn't totally know what you mean by debug panel, but here is one more video demonstrating the situation: 

[Video.webm](https://user-images.githubusercontent.com/52178013/217184468-40d66791-129c-4f56-ba2a-7544569332de.webm)

It seems like it will never fully start the service worker and just redirect to that URL again, and the same process happens again and again.

**Comment by erikpeik** [comment]
In the end, you can see, I could bypass that infinite loop, with a debugger when going step by step. It let me go to the front page finally.

**Comment by guillaume-chervet** [comment]
Hi @erikpeik , i do not know what is happening. I would like to find a solution.

**Comment by guillaume-chervet** [comment]
hi @erikpeik,

I have publish version 6.14.3-alpha0 for a try.
It may kill keep alive fetch before a service worker update.

**Comment by jafin** [comment]
@erikpeik I just experienced this as well in Firefox, (fine in chrome/Edge), the demo site works firefox.   I did notice that if I start a private window in firefox, the site will load.  I am no closer to an explanation at the moment though. using 6.14.9

**Comment by guillaume-chervet** [comment]
Oo i understand , Firefox does not allow service worker in private mode. In a strange way. I have to detect it and disable service worker mode in private.

**Comment by jafin** [comment]
Ok I found my issue with Firefox, My app originated from CRA.  The entry point after root.Render has this in the boilerplate code

```ts
// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();
```

Which appears fine in Chrome/Edge.  But Firefox was getting into the described issue above.
Commenting out the line fixed the loop.

I wasn't able to debug this, but the CRA serviceworker.ts has this reload code (perhaps this is triggering the page reload.

```ts
function checkValidServiceWorker(swUrl: string, config?: Config) {
    // Check if the service worker can be found. If it can't reload the page.
    fetch(swUrl)
        .then((response) => {
            // Ensure service worker exists, and that we really are getting a JS file.
            const contentType = response.headers.get('content-type');
            if (response.status === 404 || (contentType != null && contentType.indexOf('javascript') === -1)) {
                // No service worker found. Probably a different app. Reload the page.
                navigator.serviceWorker.ready.then((registration) => {
                    registration.unregister().then(() => {
                        window.location.reload();
                    });
                });
            } else {
                // Service worker found. Proceed as normal.
                registerValidSW(swUrl, config);
            }
        })
        .catch(() => {
            console.log('No internet connection found. App is running in offline mode.');
        });
}
```


I don't know much about service workers, are you allowed just one?   
If so perhaps there needs to be some indication there is already a service worker and complain ?

**Comment by jafin** [comment]
@erikpeik Curious, do you have a similar config with multiple service workers (oidc lib + other) ? Or was my issue different to yours?

**Comment by erikpeik** [comment]
@jafin I think I had the same issue than you. (I have that line `serviceWorker.unregister();`)  I didn't have any other service workers. I lost my hope some point and had already changed my OIDC library, but have to check this out. Thanks for the good find! :)

**Comment by guillaume-chervet** [comment]
Oo @erikpeik , you could also disable service worker by removing url to serviceworker file in configuration instead of changing of library 😜

**Comment by guillaume-chervet** [comment]
Thank you for your feedback @erikpeik , i think we can enhance documentation or crétacé a kind of FAQ.

**Comment by guillaume-chervet** [comment]
Thank you @erikpeik for your issue. I close it but feel free to open new one when you will use its library back :)
